version: '2'

services:

  nginx:
    image: nginx:1.11
    network_mode: "host"
    environment:
     - NGINX_PORT=${NGINX_PORT}
     - BACKEND_PORT=${BACKEND_PORT}
     - GRAPHIQL_PORT=${GRAPHIQL_PORT}
    volumes:
     - ./python-graphql.template:/etc/nginx/conf.d/python-graphql.template
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/python-graphql.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  graphiql:
    image: graphiql:0.1
    build:
      context: ../../src/graphiql
    environment:
     - GRAPHIQL_PORT=${GRAPHIQL_PORT}
    network_mode: "host"
    command: bash -c "yarn start"
