version: '2'

services:

  nginx:
    image: nginx:1.11
    ports:
      - "8080:${NGINX_PORT}"
    environment:
     - NGINX_PORT=${NGINX_PORT}
     - BACKEND_PORT=${BACKEND_PORT}
    volumes:
     - ./python-graphql.template:/etc/nginx/conf.d/python-graphql.template
     - ../../src/graphiql:/srv/www/graphiql
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/python-graphql.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  backend:
    image: graphql-learn:0.1
    build:
      context: ../../src/backend
      args:
        server_port: ${BACKEND_PORT}
    volumes:
     - ../../src/backend:/srv/app